### ISSUE TITLE
Run scripts from created venv

### ISSUE THREAD

**Issue by devforfu** [sjkingo/virtualenv-api#32]
The `VirtualEnvironment` class provide methods to install/uninstall packages and list them. But there is no way to activate created venv and/or run scripts using this brand new environment. 

Do you plan to add something like these methods or it is outside of project's scope and doesn't worth to be implemented?

**Comment by sjkingo** [comment]
Hi, the main goal of the project is to allow you to manage a virtual environment and its installed packages, rather than to activate it and run scripts like you would after running `bin/activate`.

It is certainly something we can look at - what use case do you have for this, where running the usual `bin/activate` script isn't suitable?

**Comment by devforfu** [comment]
Ok, I see. No, the activate is OK, I've just created a script (kind of tiny fabric) to deploy venvs and install custom packages into them. That's why I've decided to ask. Now I do it manually i.e. via `subprocess` invoking `setup.py`.

**Comment by sjkingo** [comment]
So are you doing something like this:

```
env = VirtualEnvironment('/path/to/this/env')
env.install('foobar')
...
Popen(['other_package/setup.py', 'install'])
```

If so, `env.install` can install a package using any valid pip specifier, such as `/path/to/other_package'. Or am I not understanding correctly?

**Comment by sjkingo** [comment]
I wonder if what you are describing could be generalised into a feature where you can "activate" the environment when you instantiate the `VirtualEnvironment` class? At the moment the library simply sets the current working directory when executing commands such as install, rather than run the `bin/activate` script.

This could be a valid feature, so any further calls after `VirtualEnvironment(...)` would be inside an activated environment?

**Comment by devforfu** [comment]
Yep, so far I am doing something even more awkward, like this:

```python
def deploy(path_to_package):
    env = VirtualEnvironment('/path/to/this/env')
    # keep path to brand new interpreter from this env
    ...
    Popen([path_to_env_interpreter, path_to_package_setup, 'install'])
    # do something within env where package was installed
    # e.g. 'env_python -m package_name <args>'
```

Therefore, something like standalone separate environments for each package that mostly do not interact with global score or each other.

Yes, I guess your right. Because at first my thought was like that `VirtualEnvironment` class is something that also represents "context" of the specific environment.
